### ISSUE TITLE
While installing the requirements.txt file

### ISSUE THREAD

**Issue by aravindchaluvadi** [facebookresearch/UnsupervisedQA#10]
While running the requirements.txt file i am facing the below issue ,

I am following the steps mentioned in the repository by creating a conda environment and then following the steps as mentioned.

ERROR: Command errored out with exit status 1:
     command: /home/xxxx/anaconda3/envs/uqa37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-glq8b46f/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-glq8b46f/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0554_ssy/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-glq8b46f/cffi/
    Complete output (55 lines):
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/c
    gcc -pthread -B /home/xxxx/anaconda3/envs/uqa37/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/home/xxxx/anaconda3/envs/uqa37/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xxx/anaconda3/envs/uqa37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-glq8b46f/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-glq8b46f/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0554_ssy/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rsanjaykamath** [comment]
I had a similar issue while installing. This happens due to a version error while installing a package for allennlp. 

I ran this command `sudo apt-get install build-essential` following this link "https://askubuntu.com/questions/161104/how-do-i-install-make" to install certain libraries.

**Comment by patrick-s-h-lewis** [comment]
Sorry for the delay in replying. 
Thanks Sanjay Kamath! Yes this is an error due to an allennlp requirement. I think its fixed in later versions of allennlp, but dont want to bump the version for reproducibility. 
It doenst affect everyone, hopefully Sanjay's fix will work for you aravindchaluvadi

**Comment by LCXin00** [comment]
i have same problem.
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/scw4750/anaconda3/envs/lcx_glow/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5pmkjlv0/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5pmkjlv0/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2oo14qy3 --python-tag cp35
       cwd: /tmp/pip-install-5pmkjlv0/horovod/
  Complete output (97 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
  creating build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  creating build/lib.linux-x86_64-3.5/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
  creating build/lib.linux-x86_64-3.5/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
  creating build/lib.linux-x86_64-3.5/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
  creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
  creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
  running build_ext
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -shared -L/home/scw4750/anaconda3/envs/lcx_glow/lib -Wl,-rpath=/home/scw4750/anaconda3/envs/lcx_glow/lib,--no-as-needed build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -L/home/scw4750/anaconda3/envs/lcx_glow/lib -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -shared -L/home/scw4750/anaconda3/envs/lcx_glow/lib -Wl,-rpath=/home/scw4750/anaconda3/envs/lcx_glow/lib,--no-as-needed build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.o -L/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/core -L/home/scw4750/anaconda3/envs/lcx_glow/lib -ltensorflow_framework -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.so
  /usr/bin/ld: cannot find -ltensorflow_framework
  collect2: error: ld returned 1 exit status
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -shared -L/home/scw4750/anaconda3/envs/lcx_glow/lib -Wl,-rpath=/home/scw4750/anaconda3/envs/lcx_glow/lib,--no-as-needed build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.o -L/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/core -L/home/scw4750/anaconda3/envs/lcx_glow/lib -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_libs.so
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -D_GLIBCXX_USE_CXX11_ABI=0 -I/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/include -I/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/include/external/nsync/public -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_abi.cc -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_abi.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -shared -L/home/scw4750/anaconda3/envs/lcx_glow/lib -Wl,-rpath=/home/scw4750/anaconda3/envs/lcx_glow/lib,--no-as-needed build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_abi.o -L/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/core -L/home/scw4750/anaconda3/envs/lcx_glow/lib -o build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_abi.so
  building 'horovod.tensorflow.mpi_lib' extension
  creating build/temp.linux-x86_64-3.5/horovod
  creating build/temp.linux-x86_64-3.5/horovod/tensorflow
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-3.5/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -I/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/include -I/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  g++ -pthread -shared -L/home/scw4750/anaconda3/envs/lcx_glow/lib -Wl,-rpath=/home/scw4750/anaconda3/envs/lcx_glow/lib,--no-as-needed build/temp.linux-x86_64-3.5/horovod/tensorflow/mpi_ops.o -L/home/scw4750/anaconda3/envs/lcx_glow/lib -lpython3.5m -o build/lib.linux-x86_64-3.5/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -L/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/tensorflow/core
  INFO: Above error indicates that this PyTorch installation does not support CUDA.
  INFO: Unable to build PyTorch plugin, will skip it.

  Traceback (most recent call last):
    File "/tmp/pip-install-5pmkjlv0/horovod/setup.py", line 572, in build_extensions
      build_torch_extension(self, options, abi_compile_flags)
    File "/tmp/pip-install-5pmkjlv0/horovod/setup.py", line 509, in build_torch_extension
      from torch.utils.ffi import create_extension
    File "/home/scw4750/anaconda3/envs/lcx_glow/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
      raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
  ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

  building 'horovod.common.mpi_lib' extension
  creating build/temp.linux-x86_64-3.5/horovod/common
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c horovod/common/common.cc -o build/temp.linux-x86_64-3.5/horovod/common/common.o -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c horovod/common/mpi_message.cc -o build/temp.linux-x86_64-3.5/horovod/common/mpi_message.o -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/scw4750/anaconda3/envs/lcx_glow/include/python3.5m -c horovod/common/operations.cc -o build/temp.linux-x86_64-3.5/horovod/common/operations.o -std=c++11 -fPIC -O2 -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -pthread -L/usr//lib -L/usr/lib/openmpi/lib -lmpi_cxx -lmpi -ldl -lhwloc -D_GLIBCXX_USE_CXX11_ABI=0
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /usr/lib/openmpi/include/mpi.h:253:0,
                   from horovod/common/operations.cc:36:
  /usr/lib/openmpi/include/mpi_portable_platform.h:374:34: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                    ^
  /usr/lib/openmpi/include/mpi_portable_platform.h:374:63: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                _STRINGIFY(__GNUC__)"."_STRINGIFY(__GNUC_MINOR__)"."_STRINGIFY(__GNUC_PATCHLEVEL__)
                                                                 ^
  horovod/common/operations.cc: In function ‘void horovod::common::{anonymous}::PerformOperation(horovod::common::{anonymous}::TensorTable&, horovod::common::MPIResponse)’:
  horovod/common/operations.cc:784:24: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
           e.tensor->data(), (int)e.tensor->shape().num_elements(),
                          ^
  In file included from horovod/common/operations.cc:36:0:
  /usr/lib/openmpi/include/mpi.h:1036:20: note: initializing argument 1 of ‘int MPI_Allgatherv(void*, int, MPI_Datatype, void*, int*, int*, MPI_Datatype, MPI_Comm)’
   OMPI_DECLSPEC  int MPI_Allgatherv(void *sendbuf, int sendcount, MPI_Datatype sendtype,
                      ^
  horovod/common/operations.cc:1106:54: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
                                 horovod_global.mpi_comm))
                                                        ^
  horovod/common/operations.cc:530:24: note: in definition of macro ‘MPI_CHECK’
       auto mpi_result = (op);                                                    \
                          ^
  In file included from horovod/common/operations.cc:36:0:
  /usr/lib/openmpi/include/mpi.h:1041:20: note: initializing argument 1 of ‘int MPI_Allreduce(void*, void*, int, MPI_Datatype, MPI_Op, MPI_Comm)’
   OMPI_DECLSPEC  int MPI_Allreduce(void *sendbuf, void *recvbuf, int count,
                      ^
  horovod/common/operations.cc: In function ‘void horovod::common::{anonymous}::BackgroundThreadLoop(horovod::common::{anonymous}::HorovodGlobalState&)’:
  horovod/common/operations.cc:1251:33: error: ‘MPI_COMM_TYPE_SHARED’ was not declared in this scope
     MPI_Comm_split_type(mpi_comm, MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL,
                                   ^
  horovod/common/operations.cc:1252:34: error: ‘MPI_Comm_split_type’ was not declared in this scope
                         &local_comm);
                                    ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for horovod

**Comment by yugaljain1999** [comment]
@rsanjaykamath Can you specify your machine configuration where you are running this whole model for question answering?
actually I have tried on kaggle but there was an error while running this command-
`python -m unsupervisedqa.generate_synthetic_qa_data example_input.txt example_output \
    --input_file_format "txt" \
    --output_file_format "jsonl,squad" \
    --translation_method unmt \
    --use_named_entity_clozes \
    --use_subclause_clozes \
    --use_wh_heuristic `
 
Error was this - 
![WhatsApp Image 2020-07-09 at 13 42 50](https://user-images.githubusercontent.com/32617984/87153573-53ebb400-c2d5-11ea-8a53-6b2525008f43.jpeg)

Meanwhile I was also getting some errors related to version incompatible while running `pip install -r requirements.txt` because of I think may be spacy,thinc or msgpack library...

Can you please help me to solve these errors? And please specify your machine configuration on which you ran this whole code?

Thanks!

**Comment by rsanjaykamath** [comment]
@yugaljain1999 can you post this on colab and share it? this particular message is hard to debug as this does not show the error concerning the requirements installation.

**Comment by yugaljain1999** [comment]
@rsanjaykamath  thanks for your reply..it was version incompatibility of sklearn which I solved using this command `pip install scikit-learn==0.22.2`.

**Comment by yugaljain1999** [comment]
@rsanjaykamath ..I again encountered same error but this time this occurred with different paragraphs which I have used..I don't know why again running all commands may encounter this error..
Here is the link of kaggle notebook where I have tried this code - https://drive.google.com/file/d/1drcznq5d9HmA2jkndyoqo8pOvoAEZBAS/view?usp=sharing

Thanks!

**Comment by yugaljain1999** [comment]
Colab notebook - https://colab.research.google.com/drive/12FjwgcW0Zi_STOhObf-Yhgft3XAgYW1w?usp=sharing
Kaggle kernel notebook - https://www.kaggle.com/ykjain/facebook-unsupervisedqa-example

**Comment by shiwang-Xing** [comment]
I ran `sudo apt-get install build-essential libssl-dev libffi-dev python-dev` to solve the `Running setup.py install for cffi ... error ERROR: Command errored out with exit status 1:`, hope will help the others.
