### ISSUE TITLE
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`

### ISSUE THREAD

**Issue by nevermet** [facebookresearch/UnsupervisedQA#20]
When I ran this command:
python -m unsupervisedqa.generate_synthetic_qa_data exmaple_input.txt example_output --input_file_format "txt" --output_file_format "jsonl,squad" --translation_method unmt

I've received this error message:
Traceback (most recent call last):
  File "/anaconda/envs/uqa37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/envs/uqa37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 19, in <module>
    from .constituency_parsing import get_constituency_parsed_clozes, shorten_cloze
  File "/home/azureuser/UnsupervisedQA/unsupervisedqa/constituency_parsing.py", line 12, in <module>
    from allennlp.models.archival import load_archive
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/models/__init__.py", line 6, in <module>
    from allennlp.models.model import Model
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/models/model.py", line 16, in <module>
    from allennlp.data import Instance, Vocabulary
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 4, in <module>
    from allennlp.data.instance import Instance
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/allennlp/data/fields/array_field.py", line 42, in ArrayField
    @overrides
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/anaconda/envs/uqa37/lib/python3.7/site-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`

Could you help me run this command, please?

**Comment by WildLight** [comment]
I have the some problem. I solved by installing the lower version of overrides==2.0.
