### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by BLAIR-wy** [facebookresearch/UnsupervisedQA#24]
Hi, When I run :
python -m unsupervisedqa.generate_synthetic_qa_data example_input.txt example_output     --input_file_format "txt"     --output_file_format "jsonl,squad"     --translation_method unmt     --use_named_entity_clozes     --use_subclause_clozes     --use_wh_heuristic 

I face this issue:
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/PyTorch-1.10.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.10.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ma-user/work/UnsupervisedQA-main/unsupervisedqa/generate_synthetic_qa_data.py", line 20, in <module>
    from .unmt_translation import get_unmt_questions_for_clozes
  File "/home/ma-user/work/UnsupervisedQA-main/unsupervisedqa/unmt_translation.py", line 21, in <module>
    from src.data.loader import check_all_data_params, load_data
ModuleNotFoundError: No module named 'src'

In unmt_translation.py, where this "src" comes from?

from src.utils import restore_segmentation
from src.model import check_mt_model_params, build_mt_model
from src.trainer import TrainerMT
from src.evaluator import EvaluatorMT

**Comment by BLAIR-wy** [comment]
@patrick-s-h-lewis

**Comment by BLAIR-wy** [comment]
I miss UnsupervisedMT, problem solved
