### ISSUE TITLE
Output memory map failed : 22.

### ISSUE THREAD

**Issue by askaydevs** [facebookresearch/UnsupervisedQA#6]
`Traceback (most recent call last):
  File "/home/askaydevs/.conda/envs/reports/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/askaydevs/.conda/envs/reports/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 165, in <module>
    generate_synthetic_training_data(args)
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 113, in generate_synthetic_training_data
    args.translation_method
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/generate_synthetic_qa_data.py", line 75, in get_questions_for_clozes
    clozes, subclause_clozes,  ne_answers,  wh_heuristic)
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/unmt_translation.py", line 316, in get_unmt_questions_for_clozes
    translation_input_path = preprocessing(clozes, tempdir, vocab_path, bpe_codes_path, wh_heuristic)
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/unmt_translation.py", line 70, in preprocessing
    _apply_bpe(tok_cloze_file, bpe_cloze_file, bpe_codes_path, vocab_path)
  File "/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/unmt_translation.py", line 39, in _apply_bpe
    subprocess.check_call(cmd, shell=True)
  File "/home/askaydevs/.conda/envs/reports/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/../UnsupervisedMT/NMT/tools/fastBPE/fast applybpe /tmp/tmp9gk9zgfa/dev.cloze.tok.bpe /tmp/tmp9gk9zgfa/dev.cloze.tok /home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/../data/subclause_ne_wh_heuristic/bpe_codes /home/askaydevs/Public/natural_language_processing/solverminds/local_ec2_uqa37/UnsupervisedQA/unsupervisedqa/../data/subclause_ne_wh_heuristic/vocab.cloze-question.60000' returned non-zero exit status 1.
[INFO/MainProcess] process shutting down`

**Comment by askaydevs** [comment]
What possibly can be this issue about?

**Comment by patrick-s-h-lewis** [comment]
please post the full output of the program and the command you ran.
Looks like the FastBPE tokenization subprocess call failed.

**Comment by patrick-s-h-lewis** [comment]
closing due to lack of activity
